### ISSUE TITLE
ImportError: No module named clic

### ISSUE THREAD

**Issue by ket0x4** [ManuelLR/Notmail_Bot#32]
`doop@doopserver:~/Notmail_Bot$ python notmail_bot.py --config_path my-config/my_config.ini
Traceback (most recent call last):
  File "notmail_bot.py", line 19, in <module>
    import click  # http://click.pocoo.org/6/
ImportError: No module named click`

I alredy installed click with pip

**Comment by ManuelLR** [comment]
@TheDoop Hi!
Can you please give me more details?
With which command did you install the dependencies?  What was his output?
I haven't this problem and I reviewed the official documentation of click and is being used correctly.

**Comment by ket0x4** [comment]
Ok
Firt I installed dependencies
`pip install -r requirements.txt`
And I tried to run
`python notmail_bot.py --config_path my-config/my_config.ini`
but this gave the output
`Traceback (most recent call last):
  File "notmail_bot.py", line 19, in <module>
    import click  # http://click.pocoo.org/6/
ImportError: No module named click`
But click module already installed 
`Requirement already satisfied: click in /usr/local/lib/python3.5/dist-packages (6.7)`
